web:
    image: nginx:latest
    ports:
        - "8081:80"
    volumes:
        - /home/msed/npm/src:/usr/share/nginx/html
        - /home/msed/npm/nginx.conf:/etc/nginx/conf.d
    links:
        - php
php:
    image: php:7-fpm
    volumes:
        - /home/msed/npm/src:/usr/share/nginx/html