web:
    image: nginx:latest
    ports:
        - "8080:80"
    volumes:
        - /home/msed/src:/src
#        - /home/msed/site.conf:/etc/nginx/conf.d/site.conf
    links:
            - php
php:
    image: php:7-fpm