web:
    image: nginx:latest
    ports:
        - "8080:80"
    volumes:
        - /home/msed/src:/usr/share/nginx/html
        - /home/msed/nginx.conf:/usr/local/nginx/conf
    links:
            - php
php:
    image: php:7-fpm
    volumes:
        - /home/msed/src:/usr/share/nginx/html    